<template>
  <div class="foo">
    <h1 class="underline">This is a <small>Hero</small></h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra enim eu aliquam porttitor. Phasellus vulputate felis id tempor gravida. Cras pharetra gravida dui, at egestas nisl cursus id. Nulla mattis neque feugiat dui vehicula, sit amet venenatis lectus pharetra. Morbi ligula ex, lacinia non commodo et, porttitor vel nisl. Proin porttitor lorem in orci aliquet, et volutpat ligula laoreet. Sed ornare gravida purus, eget vestibulum orci mollis id. Duis maximus, tellus sit amet molestie finibus, augue nunc lacinia est, sed aliquet purus dui sit amet massa. Praesent nec lorem ac enim accumsan rhoncus ut et magna. Donec a orci ac quam ultricies laoreet ut eget risus. Aenean eu sem ac elit pulvinar hendrerit.</p>
    <p>Donec a molestie nunc. Aliquam ac nisl quis tortor varius pharetra. Nulla vitae tempus turpis. Maecenas massa felis, egestas eu tellus in, tincidunt dapibus ante. Ut pellentesque risus in tortor efficitur, sit amet porttitor purus scelerisque. Etiam non faucibus ligula. Fusce congue euismod nunc ut molestie. Phasellus a massa non ex ultrices pretium et a est. Praesent non sodales arcu, ac pellentesque elit.</p>
    <p>Quisque vestibulum justo posuere nibh semper fermentum. Quisque tempor ipsum libero, non facilisis felis pharetra quis. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum non nunc mauris. Vivamus sed nulla quis elit posuere posuere nec ac lacus. Morbi in nunc cursus, malesuada dui et, tincidunt neque. Fusce arcu eros, egestas vitae ipsum quis, lobortis pulvinar lacus.</p>
    <p>Nullam pellentesque mauris id pellentesque porttitor. Proin faucibus, lectus in convallis aliquet, nunc orci tincidunt felis, tempor euismod sem mi iaculis ex. Etiam sed mi non ante semper tincidunt. Etiam rutrum nulla nec tortor consequat, et consectetur urna iaculis. Ut vitae nibh in leo finibus dapibus. Nulla facilisi. Proin posuere eros id sapien ornare, non pellentesque turpis luctus. Duis ultricies sagittis augue, eget dictum velit euismod in. Mauris sit amet convallis mauris. Nullam dignissim consequat gravida. Duis urna arcu, suscipit vel quam non, vehicula luctus ipsum.</p>
    <p>Morbi convallis, urna et maximus egestas, augue risus venenatis sapien, rhoncus porttitor turpis leo ut ipsum. Maecenas suscipit sollicitudin commodo. Proin vitae diam hendrerit, tincidunt urna eu, maximus risus. Donec enim nisl, congue et sapien ut, dignissim dignissim dolor. Praesent porta ac elit gravida aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam mollis tincidunt massa, a sagittis tortor imperdiet quis.</p>
  </div>
</template>